### ISSUE TITLE
Assets\PlayFabSdk\MultiplayerAgent\PlayFabMultiplayerAgentView.cs(12,17): error CS0103: The name 'PlayFabMultiplayerAgentAPI' does not exist in the current context

### ISSUE THREAD

**Issue by Crasiuss** [PlayFab/gsdk#53]
Hello. Today I started a new project, imported Playfab SDK from Playfab website and Playfab GSDK from Unity GSDK folder and this error comes up:

Assets\PlayFabSdk\MultiplayerAgent\PlayFabMultiplayerAgentView.cs(12,17): error CS0103: The name 'PlayFabMultiplayerAgentAPI' does not exist in the current context

Unity version: 2019.3.13f1

I tried also with the old version of GSDK linked in the description.

**Comment by dgkanatsios** [comment]
Hey, thanks for reporting this. Are you use you're using the latest version of [Unity GSDK](https://github.com/PlayFab/gsdk/tree/master/UnityGsdk/Assets/PlayFabSdk/MultiplayerAgent)? `PlayFabMultiplayerAgentAPI` is on line [40 and afterwards](https://github.com/PlayFab/gsdk/blob/master/UnityGsdk/Assets/PlayFabSdk/MultiplayerAgent/PlayFabMultiplayerAgentView.cs#L40)

**Comment by Crasiuss** [comment]
Thank you for the quick response. Yes, I used the one you just sent me, and still the same problem. If I drag the PlayFabMultiplayerSDK.unitypackage into my project and import it before UnitySDK.unitypackage, it will give me a bunch of errors such as this one:

Assets\PlayFabSdk\MultiplayerAgent\Model\GsdkConfiguration.cs(60,23): error CS0246: The type or namespace name 'PropertyName' could not be found (are you missing a using directive or an assembly reference?)

Once I import the UnitySDK.unitypackage, then it gives the first error I sent only.

I opened the MultiplayerServerSample as a different project to take a look, and it gives me a bunch of other errors.

**Comment by dgkanatsios** [comment]
Ah, you're importing the .unitypackage file. Apologies, we haven't updated that recently, there was a discussion whether to remove it and let people just import the files. We simply updated the GSDK without updating the unitypackage file. I just pushed a commit on it which includes the latest version of Unity GSDK, can you try again?
Moreover, you'll also notice that this version does *not* include [PlayFab Unity SDK](https://github.com/PlayFab/UnitySDK), you'll need to download it separately if you need to use it.

**Comment by Crasiuss** [comment]
I have done it again. I imported the Playfab Unity SDK, and then dragged everything inside UnityGSDK/Assets/PlayfabSDK into my unity project, and still shows the same error. Is there any other file that I need to drag into the project? Or is it that I must drag them into a specific folder inside the PlayfabUnitySDK folder that was created when I imported it?

**Comment by dgkanatsios** [comment]
Can you do one test for me? Just `git clone` this repository and open Unity to the folder `UnityGsdk`. This opens with no issues on my machine, using 2019.3.11f1.

On the same project, I drag-dropped [PlayFab Unity SDK](https://github.com/PlayFab/UnitySDK/blob/master/Packages/UnitySDK.unitypackage) and it works.

Here is my final folder hierarchy. Highlighted are the folders that are part of the Unity GSDK, the non-highlighted are the ones that were brought it with the drag-drop operation.
![image](https://user-images.githubusercontent.com/8256138/81461032-01b7d680-915e-11ea-8acd-75198d3da886.png)
Hope that helps!

**Comment by Crasiuss** [comment]
![unity](https://user-images.githubusercontent.com/53958156/81462091-0ab8a000-917e-11ea-9461-b5e393dce142.png)

So, I opened a new project in Unity. I cloned this repository (UnityGSDK) and dragged into the project these three folders MultiplayerServerSample, PlayFabEditorExtensions, and PlayFabSdk (which contains MultiplayerAgent folder). When I did this, a bunch of errors showed up in the console, the second error I sent preciously is one of them. Then, I downloaded the UnitySDK from your link, and dragged it into the project, where then it asked me to import everything, and I did. Once it finished, the previous errors disappeared, but the first error I sent showed up.

**Comment by dgkanatsios** [comment]
Oh, found it. You have to add the `ENABLE_PLAYFABSERVER_API` using directive in your project, this was included in one of our recent checkins. I'll amend our README to include that, apologies again for the inconvenience. Let us know if this works!

![image](https://user-images.githubusercontent.com/8256138/81462533-f23d8b00-9167-11ea-8553-d2adee009678.png)

**Comment by Crasiuss** [comment]
That solved it! Thank you for everything. I'm very new to everything related with online multiplayer, and I wanted to take a look at the samples to have an idea.

**Comment by dgkanatsios** [comment]
Great, let us know if you have any more questions!
